// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 4.2.2 by TAF Team.
// Generated from `./TgDataAsync.jce'
// **********************************************************************

var TafStream = require('@taf/taf-stream');
var TafError  = require('@taf/taf-rpc').error;

if(TafStream.JceStruct == undefined){
TafStream.JceStruct = function() {
this._jce_double_precision_ = -1;
}
TafStream.JceStruct.prototype.setPrecision = function(d) {
if ((d == -1) || (d >= 0 && d <= 15)) {
this._jce_double_precision_ = d;
return true;
}
return false;
}
TafStream.JceStruct.prototype.resetPrecision = function() { this._jce_double_precision_ = -1;}
TafStream.JceStruct.prototype.hasSetPrecision = function() { return (this._jce_double_precision_ >= 0 && this._jce_double_precision_ <= 15);}
TafStream.JceStruct.prototype.getPrecision = function() { return this._jce_double_precision_; }
}

var ETG = ETG || {};
module.exports.ETG = ETG;

ETG.TgDataAsyncProxy = function () {
    this._name   = undefined;
    this._worker = undefined;
}

ETG.TgDataAsyncProxy.prototype.setTimeout = function (iTimeout) {
    this._worker.timeout = iTimeout;
}

ETG.TgDataAsyncProxy.prototype.getTimeout = function ( ) {
    return this._worker.timeout;
}


ETG.SelectReq = function() {
    this.sql = "";
    this.param = "";
    this._classname = "ETG.SelectReq";
};
ETG.SelectReq.prototype = new TafStream.JceStruct();
ETG.SelectReq._classname = "ETG.SelectReq";

ETG.SelectReq._write = function (os, tag, value) { os.writeStruct(tag, value); }
ETG.SelectReq._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
ETG.SelectReq._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new ETG.SelectReq();
    tmp.sql = is.readString(0, false, "");
    tmp.param = is.readString(1, false, "");
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
ETG.SelectReq.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    if (this.sql != undefined && this.sql != "") {
        os.writeString(0, this.sql);
    }
    if (this.param != undefined && this.param != "") {
        os.writeString(1, this.param);
    }
    os.resumePrecision && os.resumePrecision();
};
ETG.SelectReq.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
ETG.SelectReq.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
ETG.SelectReq.prototype.toObject = function() { 
    var tmp = {};

    tmp.sql = this.sql;
    tmp.param = this.param;
    
    return tmp;
}
ETG.SelectReq.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("sql") || (this.sql = json.sql);
    !json.hasOwnProperty("param") || (this.param = json.param);
}
ETG.SelectReq.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
ETG.SelectReq.new = function () {
    return new ETG.SelectReq();
}
ETG.SelectReq.create = function (is) {
    return ETG.SelectReq._readFrom(is);
}
ETG.SelectRsp = function() {
    this.iRet = 0;
    this.result = "";
    this.error = "";
    this._classname = "ETG.SelectRsp";
};
ETG.SelectRsp.prototype = new TafStream.JceStruct();
ETG.SelectRsp._classname = "ETG.SelectRsp";

ETG.SelectRsp._write = function (os, tag, value) { os.writeStruct(tag, value); }
ETG.SelectRsp._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
ETG.SelectRsp._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new ETG.SelectRsp();
    tmp.iRet = is.readInt32(0, false, 0);
    tmp.result = is.readString(1, false, "");
    tmp.error = is.readString(2, false, "");
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
ETG.SelectRsp.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    if (this.iRet != undefined && this.iRet != 0) {
        os.writeInt32(0, this.iRet);
    }
    if (this.result != undefined && this.result != "") {
        os.writeString(1, this.result);
    }
    if (this.error != undefined && this.error != "") {
        os.writeString(2, this.error);
    }
    os.resumePrecision && os.resumePrecision();
};
ETG.SelectRsp.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
ETG.SelectRsp.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
ETG.SelectRsp.prototype.toObject = function() { 
    var tmp = {};

    tmp.iRet = this.iRet;
    tmp.result = this.result;
    tmp.error = this.error;
    
    return tmp;
}
ETG.SelectRsp.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("iRet") || (this.iRet = json.iRet);
    !json.hasOwnProperty("result") || (this.result = json.result);
    !json.hasOwnProperty("error") || (this.error = json.error);
}
ETG.SelectRsp.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
ETG.SelectRsp.new = function () {
    return new ETG.SelectRsp();
}
ETG.SelectRsp.create = function (is) {
    return ETG.SelectRsp._readFrom(is);
}
ETG.UpdateReq = function() {
    this.table = "";
    this.data = "";
    this.where = "";
    this.param = "";
    this.async = 0;
    this._classname = "ETG.UpdateReq";
};
ETG.UpdateReq.prototype = new TafStream.JceStruct();
ETG.UpdateReq._classname = "ETG.UpdateReq";

ETG.UpdateReq._write = function (os, tag, value) { os.writeStruct(tag, value); }
ETG.UpdateReq._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
ETG.UpdateReq._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new ETG.UpdateReq();
    tmp.table = is.readString(0, false, "");
    tmp.data = is.readString(1, false, "");
    tmp.where = is.readString(2, false, "");
    tmp.param = is.readString(3, false, "");
    tmp.async = is.readInt32(4, false, 0);
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
ETG.UpdateReq.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    if (this.table != undefined && this.table != "") {
        os.writeString(0, this.table);
    }
    if (this.data != undefined && this.data != "") {
        os.writeString(1, this.data);
    }
    if (this.where != undefined && this.where != "") {
        os.writeString(2, this.where);
    }
    if (this.param != undefined && this.param != "") {
        os.writeString(3, this.param);
    }
    if (this.async != undefined && this.async != 0) {
        os.writeInt32(4, this.async);
    }
    os.resumePrecision && os.resumePrecision();
};
ETG.UpdateReq.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
ETG.UpdateReq.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
ETG.UpdateReq.prototype.toObject = function() { 
    var tmp = {};

    tmp.table = this.table;
    tmp.data = this.data;
    tmp.where = this.where;
    tmp.param = this.param;
    tmp.async = this.async;
    
    return tmp;
}
ETG.UpdateReq.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("table") || (this.table = json.table);
    !json.hasOwnProperty("data") || (this.data = json.data);
    !json.hasOwnProperty("where") || (this.where = json.where);
    !json.hasOwnProperty("param") || (this.param = json.param);
    !json.hasOwnProperty("async") || (this.async = json.async);
}
ETG.UpdateReq.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
ETG.UpdateReq.new = function () {
    return new ETG.UpdateReq();
}
ETG.UpdateReq.create = function (is) {
    return ETG.UpdateReq._readFrom(is);
}
ETG.UpdateRsp = function() {
    this.iRet = 0;
    this.result = 0;
    this.error = "";
    this._classname = "ETG.UpdateRsp";
};
ETG.UpdateRsp.prototype = new TafStream.JceStruct();
ETG.UpdateRsp._classname = "ETG.UpdateRsp";

ETG.UpdateRsp._write = function (os, tag, value) { os.writeStruct(tag, value); }
ETG.UpdateRsp._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
ETG.UpdateRsp._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new ETG.UpdateRsp();
    tmp.iRet = is.readInt32(0, false, 0);
    tmp.result = is.readInt32(1, false, 0);
    tmp.error = is.readString(2, false, "");
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
ETG.UpdateRsp.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    if (this.iRet != undefined && this.iRet != 0) {
        os.writeInt32(0, this.iRet);
    }
    if (this.result != undefined && this.result != 0) {
        os.writeInt32(1, this.result);
    }
    if (this.error != undefined && this.error != "") {
        os.writeString(2, this.error);
    }
    os.resumePrecision && os.resumePrecision();
};
ETG.UpdateRsp.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
ETG.UpdateRsp.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
ETG.UpdateRsp.prototype.toObject = function() { 
    var tmp = {};

    tmp.iRet = this.iRet;
    tmp.result = this.result;
    tmp.error = this.error;
    
    return tmp;
}
ETG.UpdateRsp.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("iRet") || (this.iRet = json.iRet);
    !json.hasOwnProperty("result") || (this.result = json.result);
    !json.hasOwnProperty("error") || (this.error = json.error);
}
ETG.UpdateRsp.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
ETG.UpdateRsp.new = function () {
    return new ETG.UpdateRsp();
}
ETG.UpdateRsp.create = function (is) {
    return ETG.UpdateRsp._readFrom(is);
}
ETG.InsertReq = function() {
    this.table = "";
    this.data = "";
    this.async = 0;
    this._classname = "ETG.InsertReq";
};
ETG.InsertReq.prototype = new TafStream.JceStruct();
ETG.InsertReq._classname = "ETG.InsertReq";

ETG.InsertReq._write = function (os, tag, value) { os.writeStruct(tag, value); }
ETG.InsertReq._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
ETG.InsertReq._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new ETG.InsertReq();
    tmp.table = is.readString(0, false, "");
    tmp.data = is.readString(1, false, "");
    tmp.async = is.readInt32(2, false, 0);
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
ETG.InsertReq.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    if (this.table != undefined && this.table != "") {
        os.writeString(0, this.table);
    }
    if (this.data != undefined && this.data != "") {
        os.writeString(1, this.data);
    }
    if (this.async != undefined && this.async != 0) {
        os.writeInt32(2, this.async);
    }
    os.resumePrecision && os.resumePrecision();
};
ETG.InsertReq.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
ETG.InsertReq.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
ETG.InsertReq.prototype.toObject = function() { 
    var tmp = {};

    tmp.table = this.table;
    tmp.data = this.data;
    tmp.async = this.async;
    
    return tmp;
}
ETG.InsertReq.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("table") || (this.table = json.table);
    !json.hasOwnProperty("data") || (this.data = json.data);
    !json.hasOwnProperty("async") || (this.async = json.async);
}
ETG.InsertReq.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
ETG.InsertReq.new = function () {
    return new ETG.InsertReq();
}
ETG.InsertReq.create = function (is) {
    return ETG.InsertReq._readFrom(is);
}
ETG.InsertRsp = function() {
    this.iRet = 0;
    this.result = 0;
    this.error = "";
    this._classname = "ETG.InsertRsp";
};
ETG.InsertRsp.prototype = new TafStream.JceStruct();
ETG.InsertRsp._classname = "ETG.InsertRsp";

ETG.InsertRsp._write = function (os, tag, value) { os.writeStruct(tag, value); }
ETG.InsertRsp._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
ETG.InsertRsp._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new ETG.InsertRsp();
    tmp.iRet = is.readInt32(0, false, 0);
    tmp.result = is.readInt32(1, false, 0);
    tmp.error = is.readString(2, false, "");
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
ETG.InsertRsp.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    if (this.iRet != undefined && this.iRet != 0) {
        os.writeInt32(0, this.iRet);
    }
    if (this.result != undefined && this.result != 0) {
        os.writeInt32(1, this.result);
    }
    if (this.error != undefined && this.error != "") {
        os.writeString(2, this.error);
    }
    os.resumePrecision && os.resumePrecision();
};
ETG.InsertRsp.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
ETG.InsertRsp.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
ETG.InsertRsp.prototype.toObject = function() { 
    var tmp = {};

    tmp.iRet = this.iRet;
    tmp.result = this.result;
    tmp.error = this.error;
    
    return tmp;
}
ETG.InsertRsp.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("iRet") || (this.iRet = json.iRet);
    !json.hasOwnProperty("result") || (this.result = json.result);
    !json.hasOwnProperty("error") || (this.error = json.error);
}
ETG.InsertRsp.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
ETG.InsertRsp.new = function () {
    return new ETG.InsertRsp();
}
ETG.InsertRsp.create = function (is) {
    return ETG.InsertRsp._readFrom(is);
}
ETG.ReplaceReq = function() {
    this.table = "";
    this.data = "";
    this.async = 0;
    this._classname = "ETG.ReplaceReq";
};
ETG.ReplaceReq.prototype = new TafStream.JceStruct();
ETG.ReplaceReq._classname = "ETG.ReplaceReq";

ETG.ReplaceReq._write = function (os, tag, value) { os.writeStruct(tag, value); }
ETG.ReplaceReq._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
ETG.ReplaceReq._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new ETG.ReplaceReq();
    tmp.table = is.readString(0, false, "");
    tmp.data = is.readString(1, false, "");
    tmp.async = is.readInt32(2, false, 0);
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
ETG.ReplaceReq.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    if (this.table != undefined && this.table != "") {
        os.writeString(0, this.table);
    }
    if (this.data != undefined && this.data != "") {
        os.writeString(1, this.data);
    }
    if (this.async != undefined && this.async != 0) {
        os.writeInt32(2, this.async);
    }
    os.resumePrecision && os.resumePrecision();
};
ETG.ReplaceReq.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
ETG.ReplaceReq.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
ETG.ReplaceReq.prototype.toObject = function() { 
    var tmp = {};

    tmp.table = this.table;
    tmp.data = this.data;
    tmp.async = this.async;
    
    return tmp;
}
ETG.ReplaceReq.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("table") || (this.table = json.table);
    !json.hasOwnProperty("data") || (this.data = json.data);
    !json.hasOwnProperty("async") || (this.async = json.async);
}
ETG.ReplaceReq.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
ETG.ReplaceReq.new = function () {
    return new ETG.ReplaceReq();
}
ETG.ReplaceReq.create = function (is) {
    return ETG.ReplaceReq._readFrom(is);
}
ETG.ReplaceRsp = function() {
    this.iRet = 0;
    this.result = 0;
    this.error = "";
    this._classname = "ETG.ReplaceRsp";
};
ETG.ReplaceRsp.prototype = new TafStream.JceStruct();
ETG.ReplaceRsp._classname = "ETG.ReplaceRsp";

ETG.ReplaceRsp._write = function (os, tag, value) { os.writeStruct(tag, value); }
ETG.ReplaceRsp._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
ETG.ReplaceRsp._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new ETG.ReplaceRsp();
    tmp.iRet = is.readInt32(0, false, 0);
    tmp.result = is.readInt32(1, false, 0);
    tmp.error = is.readString(2, false, "");
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
ETG.ReplaceRsp.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    if (this.iRet != undefined && this.iRet != 0) {
        os.writeInt32(0, this.iRet);
    }
    if (this.result != undefined && this.result != 0) {
        os.writeInt32(1, this.result);
    }
    if (this.error != undefined && this.error != "") {
        os.writeString(2, this.error);
    }
    os.resumePrecision && os.resumePrecision();
};
ETG.ReplaceRsp.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
ETG.ReplaceRsp.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
ETG.ReplaceRsp.prototype.toObject = function() { 
    var tmp = {};

    tmp.iRet = this.iRet;
    tmp.result = this.result;
    tmp.error = this.error;
    
    return tmp;
}
ETG.ReplaceRsp.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("iRet") || (this.iRet = json.iRet);
    !json.hasOwnProperty("result") || (this.result = json.result);
    !json.hasOwnProperty("error") || (this.error = json.error);
}
ETG.ReplaceRsp.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
ETG.ReplaceRsp.new = function () {
    return new ETG.ReplaceRsp();
}
ETG.ReplaceRsp.create = function (is) {
    return ETG.ReplaceRsp._readFrom(is);
}
ETG.DeleteReq = function() {
    this.table = "";
    this.where = "";
    this.param = "";
    this.async = 0;
    this._classname = "ETG.DeleteReq";
};
ETG.DeleteReq.prototype = new TafStream.JceStruct();
ETG.DeleteReq._classname = "ETG.DeleteReq";

ETG.DeleteReq._write = function (os, tag, value) { os.writeStruct(tag, value); }
ETG.DeleteReq._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
ETG.DeleteReq._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new ETG.DeleteReq();
    tmp.table = is.readString(0, false, "");
    tmp.where = is.readString(1, false, "");
    tmp.param = is.readString(2, false, "");
    tmp.async = is.readInt32(3, false, 0);
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
ETG.DeleteReq.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    if (this.table != undefined && this.table != "") {
        os.writeString(0, this.table);
    }
    if (this.where != undefined && this.where != "") {
        os.writeString(1, this.where);
    }
    if (this.param != undefined && this.param != "") {
        os.writeString(2, this.param);
    }
    if (this.async != undefined && this.async != 0) {
        os.writeInt32(3, this.async);
    }
    os.resumePrecision && os.resumePrecision();
};
ETG.DeleteReq.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
ETG.DeleteReq.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
ETG.DeleteReq.prototype.toObject = function() { 
    var tmp = {};

    tmp.table = this.table;
    tmp.where = this.where;
    tmp.param = this.param;
    tmp.async = this.async;
    
    return tmp;
}
ETG.DeleteReq.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("table") || (this.table = json.table);
    !json.hasOwnProperty("where") || (this.where = json.where);
    !json.hasOwnProperty("param") || (this.param = json.param);
    !json.hasOwnProperty("async") || (this.async = json.async);
}
ETG.DeleteReq.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
ETG.DeleteReq.new = function () {
    return new ETG.DeleteReq();
}
ETG.DeleteReq.create = function (is) {
    return ETG.DeleteReq._readFrom(is);
}
ETG.DeleteRsp = function() {
    this.iRet = 0;
    this.result = 0;
    this.error = "";
    this._classname = "ETG.DeleteRsp";
};
ETG.DeleteRsp.prototype = new TafStream.JceStruct();
ETG.DeleteRsp._classname = "ETG.DeleteRsp";

ETG.DeleteRsp._write = function (os, tag, value) { os.writeStruct(tag, value); }
ETG.DeleteRsp._read  = function (is, tag, def) { return is.readStruct(tag, true, def); }
ETG.DeleteRsp._readFrom = function (is) {
    if(is.readResumePrecision == undefined){
        is.readResumePrecision = function(){
            return -1;
        }
    }
    is.saveResetPrecision && is.saveResetPrecision();
    var tmp = new ETG.DeleteRsp();
    tmp.iRet = is.readInt32(0, false, 0);
    tmp.result = is.readInt32(1, false, 0);
    tmp.error = is.readString(2, false, "");
    tmp._jce_double_precision_ = is.readResumePrecision();
    return tmp;
};
ETG.DeleteRsp.prototype._writeTo = function (os) {
    os.savePrecision && os.savePrecision(this._jce_double_precision_);
    if (this.iRet != undefined && this.iRet != 0) {
        os.writeInt32(0, this.iRet);
    }
    if (this.result != undefined && this.result != 0) {
        os.writeInt32(1, this.result);
    }
    if (this.error != undefined && this.error != "") {
        os.writeString(2, this.error);
    }
    os.resumePrecision && os.resumePrecision();
};
ETG.DeleteRsp.prototype._equal = function (anItem) {
    assert(false, 'this structure not define key operation');
}
ETG.DeleteRsp.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = 'STRUCT' + Math.random();
    }
    return this._proto_struct_name_;
}
ETG.DeleteRsp.prototype.toObject = function() { 
    var tmp = {};

    tmp.iRet = this.iRet;
    tmp.result = this.result;
    tmp.error = this.error;
    
    return tmp;
}
ETG.DeleteRsp.prototype.readFromObject = function(json) { 
    !json.hasOwnProperty("iRet") || (this.iRet = json.iRet);
    !json.hasOwnProperty("result") || (this.result = json.result);
    !json.hasOwnProperty("error") || (this.error = json.error);
}
ETG.DeleteRsp.prototype.toBinBuffer = function () {
    var os = new TafStream.JceOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
}
ETG.DeleteRsp.new = function () {
    return new ETG.DeleteRsp();
}
ETG.DeleteRsp.create = function (is) {
    return ETG.DeleteRsp._readFrom(is);
}

ETG.TgDataAsyncProxy.prototype.delete = function (stReq) {
    var _encode = function () { 
        var os = new TafStream.JceOutputStream();
        os.writeStruct(1, stReq);
        return os.getBinBuffer();
    }

    var _decode = function (data) {
        try {
            var response = {arguments:{}};
            var is = new TafStream.JceInputStream(data.response.sBuffer);

            response.costtime = data.request.costtime;
            response.return   = is.readInt32(0, true, TafStream.Int32);
            response.arguments.stRsp = is.readStruct(2, true, ETG.DeleteRsp);

            return {request:data.request, response:response};
        } catch (e) {
            var response = { };
            response.costtime      = data.request.costtime;
            response.error         = {};
            response.error.code    = TafError.CLIENT.DECODE_ERROR;
            response.error.message = e.message;

            throw { request : data.request, response : response};
        }
    }

    var _error = function(data) {
        var response = {};
        response.costtime = data.request.costtime;
        response.error    = data.error;

        throw {request:data.request, response:response};
    }

    return this._worker.taf_invoke('delete', _encode(), arguments.length != 0?arguments[arguments.length - 1]:undefined).then(_decode, _error);
}

ETG.TgDataAsyncProxy.prototype.insert = function (stReq) {
    var _encode = function () { 
        var os = new TafStream.JceOutputStream();
        os.writeStruct(1, stReq);
        return os.getBinBuffer();
    }

    var _decode = function (data) {
        try {
            var response = {arguments:{}};
            var is = new TafStream.JceInputStream(data.response.sBuffer);

            response.costtime = data.request.costtime;
            response.return   = is.readInt32(0, true, TafStream.Int32);
            response.arguments.stRsp = is.readStruct(2, true, ETG.InsertRsp);

            return {request:data.request, response:response};
        } catch (e) {
            var response = { };
            response.costtime      = data.request.costtime;
            response.error         = {};
            response.error.code    = TafError.CLIENT.DECODE_ERROR;
            response.error.message = e.message;

            throw { request : data.request, response : response};
        }
    }

    var _error = function(data) {
        var response = {};
        response.costtime = data.request.costtime;
        response.error    = data.error;

        throw {request:data.request, response:response};
    }

    return this._worker.taf_invoke('insert', _encode(), arguments.length != 0?arguments[arguments.length - 1]:undefined).then(_decode, _error);
}

ETG.TgDataAsyncProxy.prototype.replace = function (stReq) {
    var _encode = function () { 
        var os = new TafStream.JceOutputStream();
        os.writeStruct(1, stReq);
        return os.getBinBuffer();
    }

    var _decode = function (data) {
        try {
            var response = {arguments:{}};
            var is = new TafStream.JceInputStream(data.response.sBuffer);

            response.costtime = data.request.costtime;
            response.return   = is.readInt32(0, true, TafStream.Int32);
            response.arguments.stRsp = is.readStruct(2, true, ETG.ReplaceRsp);

            return {request:data.request, response:response};
        } catch (e) {
            var response = { };
            response.costtime      = data.request.costtime;
            response.error         = {};
            response.error.code    = TafError.CLIENT.DECODE_ERROR;
            response.error.message = e.message;

            throw { request : data.request, response : response};
        }
    }

    var _error = function(data) {
        var response = {};
        response.costtime = data.request.costtime;
        response.error    = data.error;

        throw {request:data.request, response:response};
    }

    return this._worker.taf_invoke('replace', _encode(), arguments.length != 0?arguments[arguments.length - 1]:undefined).then(_decode, _error);
}

ETG.TgDataAsyncProxy.prototype.select = function (stReq) {
    var _encode = function () { 
        var os = new TafStream.JceOutputStream();
        os.writeStruct(1, stReq);
        return os.getBinBuffer();
    }

    var _decode = function (data) {
        try {
            var response = {arguments:{}};
            var is = new TafStream.JceInputStream(data.response.sBuffer);

            response.costtime = data.request.costtime;
            response.return   = is.readInt32(0, true, TafStream.Int32);
            response.arguments.stRsp = is.readStruct(2, true, ETG.SelectRsp);

            return {request:data.request, response:response};
        } catch (e) {
            var response = { };
            response.costtime      = data.request.costtime;
            response.error         = {};
            response.error.code    = TafError.CLIENT.DECODE_ERROR;
            response.error.message = e.message;

            throw { request : data.request, response : response};
        }
    }

    var _error = function(data) {
        var response = {};
        response.costtime = data.request.costtime;
        response.error    = data.error;

        throw {request:data.request, response:response};
    }

    return this._worker.taf_invoke('select', _encode(), arguments.length != 0?arguments[arguments.length - 1]:undefined).then(_decode, _error);
}

ETG.TgDataAsyncProxy.prototype.update = function (stReq) {
    var _encode = function () { 
        var os = new TafStream.JceOutputStream();
        os.writeStruct(1, stReq);
        return os.getBinBuffer();
    }

    var _decode = function (data) {
        try {
            var response = {arguments:{}};
            var is = new TafStream.JceInputStream(data.response.sBuffer);

            response.costtime = data.request.costtime;
            response.return   = is.readInt32(0, true, TafStream.Int32);
            response.arguments.stRsp = is.readStruct(2, true, ETG.UpdateRsp);

            return {request:data.request, response:response};
        } catch (e) {
            var response = { };
            response.costtime      = data.request.costtime;
            response.error         = {};
            response.error.code    = TafError.CLIENT.DECODE_ERROR;
            response.error.message = e.message;

            throw { request : data.request, response : response};
        }
    }

    var _error = function(data) {
        var response = {};
        response.costtime = data.request.costtime;
        response.error    = data.error;

        throw {request:data.request, response:response};
    }

    return this._worker.taf_invoke('update', _encode(), arguments.length != 0?arguments[arguments.length - 1]:undefined).then(_decode, _error);
}



